### ISSUE TITLE
"Failed to get chain" error ignored

### ISSUE THREAD

**Issue by glpuga** [mikeferguson/robot_calibration#103]
In the code below, whenever the chain tip is not part of the robot description an error is printed but the code flow is not changed. The optimizer is run despite the problem and the calibration procedure looks ok, but the optimization converges to incorrect values.

https://github.com/mikeferguson/robot_calibration/blob/ros1/robot_calibration/src/models.cpp#L45

This can happen if the robot description loaded is not the expected version or if it does not have the required features enabled.

Would it be ok if I propose a patch to throw an exception here instead?

**Comment by mikeferguson** [comment]
Yeah, that seems like an oversight. PR welcome.
