### ISSUE TITLE
"Press key when arm is ready..." message confusing when not doing arm calibration

### ISSUE THREAD

**Issue by glpuga** [mikeferguson/robot_calibration#104]
The "Press key when arm is ready..." message may not be totally clear for static robots that only do static sensor calibrations (depth camera to floor, for instance).

https://github.com/mikeferguson/robot_calibration/blob/ros1/robot_calibration/src/calibrate.cpp#L173

Would it be ok if I create a PR with a patch for this message?

**Comment by mikeferguson** [comment]
Yes, a PR would be welcome
