### ISSUE TITLE
Does it matter if the checkerboard is rotated 180* in some samples?

### ISSUE THREAD

**Issue by AndyZe** [mikeferguson/robot_calibration#139]
After a large amount of effort, we are finally getting good hand/eye, eye/eye, and kinematic calibrations from this package  :+1:

But I've been wondering this:

We have a checkerboard target bolted to the end effector. Does it matter it we accidentally flip the checkerboad 180* while collecting samples? It seems like it would cause a ton of error since the checkerboard looks the same if rotated 180* and the pose of the checkerboard is what matters (if I understand correctly).

Here's what I mean. We do kinematic calibration something like this:
![robot_cal1](https://user-images.githubusercontent.com/11284393/178888450-c5fdee18-97d5-4e3c-b6d9-0e477d359b6c.jpeg)

But while moving the robot to collect samples, we accidentally rotate the checkerboard like this. The checkboard orientation probably still looks the same to the camera.
![robot_cal2](https://user-images.githubusercontent.com/11284393/178888509-1ba59df0-0003-4bee-9260-92c834b28a25.jpeg)

**Comment by mikeferguson** [comment]
Yeah - I've run into this before when I just grabbed any old checkerboard - the trick is you need to use a checkerboard that isn't symmetric. Based on your image, if you have a checkerboard with one less row in either of the dimensions then the checkerboard finder will always find the correct orientation

**Comment by AndyZe** [comment]
Duh - thanks
