### ISSUE TITLE
Mobile robot camera extrinsic calibration

### ISSUE THREAD

**Issue by dimaxano** [mikeferguson/robot_calibration#148]
Hello!

Thank you for the work!

I do not quite understand if I'm able to find 3D camera extrinsic params (camera -> base_link  transform) with that package?

**Comment by mikeferguson** [comment]
You might be able to do this - if you have other sensors to align with. If all you have is a camera on a mobile base, I don't think this would work out of the box (we don't have any "sensor" that deals with odometry of the base, which would allow you to move relative to a fixed checkerboard)
