### ISSUE TITLE
Calibration with Laser Tracker

### ISSUE THREAD

**Issue by garyraise** [mikeferguson/robot_calibration#161]
Hi, we're looking to calibrate a 6DOF cobot arm to improve absolute accuracy, and we'd like to use a laser tracker which measures points to a reflector for providing data. Is it possible to provide only XYZ coordinates for a particular measurement instead of a full 6 DOF pose with this repo?

**Comment by mikeferguson** [comment]
Apologies - I did not see this issue get posted.

It's absolutely possible to use just points - check out the checkerboard finder and the chain3d_to_chain3d cost function - the checkerboard is represented as two series of points (one series that are the "ideal" checkerboard if it were exactly at the desired pose in the hand, the second being the observed point locations in 3d).
