### ISSUE TITLE
where can i get the checkerboard image?

### ISSUE THREAD

**Issue by cncowboy** [mikeferguson/robot_calibration#163]
where can i get the checkerboard image?

**Comment by mikeferguson** [comment]
There are some larger checkerboards on the ROS wiki - https://wiki.ros.org/camera_calibration/Tutorials/MonocularCalibration

But also a lot more options here: https://markhedleyjones.com/projects/calibration-checkerboard-collection

**Comment by mikeferguson** [comment]
Added a link to that tool in the README: https://github.com/mikeferguson/robot_calibration/commit/c3d1236af1ba453488100f2dcb72b288d612b2c8
