### ISSUE TITLE
Regression on `RHEL 9` due to `geometric_shapes` missing `fcl-devel`

### ISSUE THREAD

**Issue by marcoag** [mikeferguson/robot_calibration#164]
Just giving a heads up that this package has a [regression for Jazzy RHEL 9](https://build.ros2.org/view/Jbin_rhel_el964/job/Jbin_rhel_el964__robot_calibration__rhel_9_x86_64__binary/29/console) due to the [geometric_shapes](https://github.com/moveit/geometric_shapes) package [missing fcl-devel in RHEL 9](https://pkgs.org/search/?q=fcl-devel). Because of this it was automatically removed from the `RHEL 9` repo in the latest [Jazzy sync](https://discourse.ros.org/t/new-packages-for-jazzy-jalisco-2024-06-18/38240) (not for Ubuntu Noble). 

We are looking into ways to mitigate the issue but it might take some time. For more info you can check the [issue in the geometric_shapes repo](https://github.com/moveit/geometric_shapes/issues/243).

**Comment by mikeferguson** [comment]
Looks like this was fixed sometime in late June - latest builds are working
