### ISSUE TITLE
High precision gantry calibration

### ISSUE THREAD

**Issue by gseqBE** [mikeferguson/robot_calibration#176]
We are looking into available ROS2 solutions for calibrating a gantry setup(x,y,z) for a potential project.

The idea is to first have the URDF built up and adjusted to the actual gantry system. However minute adjustments are needed at certain points of the gantry envelope to remove errors due to tolerance stackups. These could be achieved using opto-interrupters at these points to calibrate the gantry head at those points in x,y,z

Can the offsets, calculated using the opto-interrupters in x,y and z, be  registered using the robot calibration package. This would update the URDF, which could then be queried. This happens every time the gantry is at these points.

Thanks!

**Comment by mikeferguson** [comment]
I feel like this package is not the right one for such a calibration, this package assumes you have many samples and basically do a sparse bundle adjustment over those samples - which is very different than simply triggering a calibration when an opto-interrupter is triggered - that's probably more like a driver level thing.

I will also note, live editing of a URDF at runtime might cause interesting issues in various ROS packages. While the URDF is passed as a topic in ROS 2, most of the ecosystem still assumes it is fixed at all times.
