### ISSUE TITLE
Usage on ROS 1 Noetic

### ISSUE THREAD

**Issue by edoardo-cioffi-1997** [mikeferguson/robot_calibration#184]
How can I use this package on Noetic? Do I need to change launch file o config files?

**Comment by mikeferguson** [comment]
You'll need to create the config files for your particular robot and calibration scenario - the README has a number of notes about this, and the fetch_calibration package and https://github.com/mikeferguson/ubr_reloaded/tree/ros1/ubr1_calibration exist as examples.
