### ISSUE TITLE
Gripper_led_action_server implementation

### ISSUE THREAD

**Issue by saurabhbansal90** [mikeferguson/robot_calibration#57]
Hello Mike,
I am using robot_calibration for my robotic arm.
And I am using the Led_finder for that purpose.

I checked the implementation in Fetch_ros, but didn't find the implementation for gripper_led_action_server.
I assume this action server implementation will be required, and led_finder can't work without that. Can you please conform this?

I tried to implement my own gripper_led_action_server, but getting lots of errors in compilation.
Please find the attached code and compilation logs file.
[gripper_led_action_server.zip](https://github.com/mikeferguson/robot_calibration/files/2099481/gripper_led_action_server.zip)

Saurabh

**Comment by mikeferguson** [comment]
The gripper action server is actually part of the fetch drivers -- which is not an open source package. That said, there is nothing special about the action server -- it simply has to turn on the appropriate LED and then return success. Have a look at the actionlib tutorials for how to implement an action server.
