### ISSUE TITLE
How to make a handEyeCalibration with 2d camera and robot_calibration package?

### ISSUE THREAD

**Issue by Jakubach** [mikeferguson/robot_calibration#67]
Hello,
I currently work with UR robot and I am focused on HandEyeCalibration and then TagDetection.
Is there any clear tutorial, how to use robot_calibration? Does it works with live transformation capturing or could I load a specific transformations from files?
Best regards,
Kuba

**Comment by mikeferguson** [comment]
We still don't handle 2d cameras - it is ticketed here: https://github.com/mikeferguson/robot_calibration/issues/41
