### ISSUE TITLE
Soft Iron Calibration

### ISSUE THREAD

**Issue by vinnnyr** [mikeferguson/robot_calibration#93]
Hello,

I know that in your blog: https://www.robotandchisel.com/2020/04/25/compass-calibration/ you wrote that soft iron calibration is to come. Is that something you are still interested in. Is this package the best place to do it, or is it somewhere else? 

If this package is the best place to do it, would you welcome a PR?

**Comment by mikeferguson** [comment]
Definitely still interested in that - but haven't had time to work on it. Would absolutely welcome a PR!

**Comment by vinnnyr** [comment]
Just as an update, I might not be working on this anytime soon. I did not realize it was not in ROS2, and that is currently a requirement for my application :)
